#pragma once
// Auto-generated by tools/convert_icons.py -- DO NOT EDIT
#include <cstdint>
#include "fb_helpers.h"  // Icon struct

extern const uint8_t kIconMinus_data[];
extern const uint8_t kIconPlus_data[];
extern const uint8_t kIconTurnBack_data[];
extern const uint8_t kIconDay_data[];
extern const uint8_t kIconNight_data[];

extern const Icon kIconMinus;
extern const Icon kIconPlus;
extern const Icon kIconTurnBack;
extern const Icon kIconDay;
extern const Icon kIconNight;
